//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBH_055.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHMUC
    {
        public DANHMUC()
        {
            this.SANPHAMs = new HashSet<SANPHAM>();
        }
    
        public int MADM { get; set; }
        public string TENDM { get; set; }
        public Nullable<int> MAMN { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
    
        public virtual MENU MENU { get; set; }
        public virtual ICollection<SANPHAM> SANPHAMs { get; set; }
    }
}
