//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBH_055.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        public MENU()
        {
            this.DANHMUCs = new HashSet<DANHMUC>();
        }
    
        public int MAMN { get; set; }
        public string TENMN { get; set; }
        public string HREF { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
    
        public virtual ICollection<DANHMUC> DANHMUCs { get; set; }
    }
}
