//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBH_055.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLBHEntities : DbContext
    {
        public QLBHEntities()
            : base("name=QLBHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADMIN> ADMINs { get; set; }
        public DbSet<CTHOADON> CTHOADONs { get; set; }
        public DbSet<DANHMUC> DANHMUCs { get; set; }
        public DbSet<HOADON> HOADONs { get; set; }
        public DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public DbSet<MENU> MENUs { get; set; }
        public DbSet<QUANGCAO> QUANGCAOs { get; set; }
        public DbSet<SANPHAM> SANPHAMs { get; set; }
        public DbSet<TINTUC> TINTUCs { get; set; }

        internal object Entry(object kHACHHANG)
        {
            throw new NotImplementedException();
        }
    }
}
